### DISCUSSION TITLE
Connection to associate a logical entity's consumption with a meter

### DISCUSSION THREAD

**Discussion by duncangreene** [google/digitalbuildings#1513] [Q&A] [answered]
Just to double check, is MEASURES an appropriate connection to use to associate a logical entity's consumption with a meter? From the example shown [here](https://github.com/google/digitalbuildings/blob/master/ontology/docs/connections.md), the MEASURES connection appears to be described to attribute load _types_ to meters, e.g. LOADTYPE_MECHANICAL, as opposed to specific entities (e.g. BLR-1, BLR-2, BLR-3 below)? Or is it intended for MEASURES to _also_ be used to associate specific logical entities?

E.g. A gas meter measuring gas consumption for 3 boilers.

```
BLR-1_GUID:
  code: BLR-1
  type:HVAC/BLR_SS_SWTC_CPC
  connections:
    GM-26_GUID: MEASURES
	
BLR-2_GUID:
  code: BLR-2
  type:HVAC/BLR_SS_SWTC_CPC
  connections:
    GM-26_GUID: MEASURES

BLR-3_GUID:
  code: BLR-3
  type:HVAC/BLR_SS_SWTC_CPC
  connections:
    GM-26_GUID: MEASURES

LOADTYPE-123_GUID:
  code: LOADTYPE-123
  type: METERS/LOADTYPE_MECHANICAL
  connections:
    GM-26_GUID: MEASURES
```

**Comment by duncangreene** [comment]
Further to this, if we have 1x [split load electricity meter](https://www.rayleigh.com/mid-certified-split-load-easywire-din-rail-mounting-multifunction-meter-ri-d360.html#:~:text=The%20meters%20contain%20two%20metering%20circuits%20in%20one%20case) measuring two circuits as below:

1. Lighting
2. Small power

How is it intended to relate those individual circuits/loads to lighting logical entities, and small power logical entities, separately? I suspect this may be where virtual entities are utilised, but I would appreciate an example if someone could please provide?

**Comment by bsimmons-onboard** [comment]
The ontology docs also mention FEEDs and power systems. `digitalbuildings/ontology/docs/building_config.md`
`FEEDS relationships between chained equipment in HVAC or power systems, as well as between terminal units and Zones.`

@shambergoldstein could you help clarify the correct connection here?

**Comment by shambersafai** [comment, marked as answer]
Measures is the appropriate connection to use, as you've shown, for the boilers or any individual device.  I think the best way to model the split load meters would be to create three virtual devices, one for each individual load and one fore the total, and use measures connections between them all as well as the equipment measured to create a hierarchy. 

E.g.:
```
EM-1-GATEWAY_GUID:
  code: EM-1-GATEWAY-CODE
  type: GATEWAYS/PASSTHROUGH
  translation:
      ...

EM-1_GUID:
  code: BLDG_CODE:EM:EM 1
  type: METERS/EM...
  links:
    EM-1-GATEWAY_GUID:
      ...

EM-1-LOAD1_GUID:
  code: BLDG_CODE:EM:EM 1-1
  type: METERS/EM...
  links:
    EM-1-GATEWAY_GUID:
      ...
  connections:
    EM-1_GUID: MEASURES

EM-1-LOAD2_GUID:
  code: BLDG_CODE:EM:EM 1-2
  type: METERS/EM...
  links:
    EM-1-GATEWAY_GUID:
      ...
  connections:
    EM-1_GUID: MEASURES

LIGHTING-ENTITY-1_GUID:
  code: LIGHTING-ENTITY-1_CODE
  type: LIGHTING/...
  translation:
      ...
  connections:
    EM-1-LOAD1_GUID: MEASURES

SMALL-POWER ENTITY-1_GUID:
  code: SMALL-POWER ENTITY-1_CODE
  type: ...
  translation:
      ...
  connections:
    EM-1-LOAD2_GUID: MEASURES
```

Only the measurements for the total of the loads would be modeled on BLDG_CODE:EM:EM 1, and the indivudal load measurements would be put on each of the according individual load meters. Any required fields on the canonical type you use for the indiviudal load EMs that aren't available at the individual load level you would mark missing. Let me know if this makes sense or if you have any concerns with it.

@bsimmons-onboard the feeds connection is used when one device provides something, typically a medium of some sort, to another. This could be used in some power applications. For example, if a generator provides electricity to specific devices. It would not be the best connection to use in this case as the meters dont physically provide anything to the devices/each other or vice versa.
