### DISCUSSION TITLE
how to model config to show aggregated data sending to a common virtual device

### DISCUSSION THREAD

**Discussion by josephedwardchang** [google/digitalbuildings#427] [Q&A] [answered]
![dboModel](https://user-images.githubusercontent.com/21256796/143988879-62bb7e5f-ff00-409a-b439-0e113a02e4f9.png)

above is the hardware and DDC-1 is sending aggregated data. right now it is sending only LDP-1 data because I haven't figured out how to add the other sensor's data just yet. In my experiments, this DBO config below with virtual device DDC-1 works with DBO telemetry validation:

![config yaml](https://user-images.githubusercontent.com/21256796/143989151-46153fda-ff74-4afe-8272-9d6e6bc17fc0.png)

but it doesn't seem quite right. because the virtual here is LDP-1 and my physical hardware DDC-1 is sending to DDC-1 iot core registered device. So I tried "reversing" my DBO model to this:

![image](https://user-images.githubusercontent.com/21256796/143989525-e42cca5b-6a87-42b3-b077-0cc8da8f1f7e.png)

which looks semantically correct but the telemetry validator doesn't seem to understand it and says there's no data coming from LDP-1. I would like to understand how DBO config:

- can be written so that I have telemetry aggregation and which telemetry validation will be able to work with?
- in as far as docs go, there's nothing about modelling aggregated sensor data being sent by a common virtual DDC-1 device to the iot core DDC-1 registered device

for completeness, my working json pointset for LDP-1 is:

    "points": {
      "water_leak_detection_alarm": {
        "units": "No-units",
        "ref": "points.water_leak_detection_alarm.present_value"
      },
      "broken_cable_alarm": {
        "units": "No-units",
        "ref": "points.broken_cable_alarm.present_value"
      },
      "water_leak_cable_distance_sensor": {
        "units": "meter",
        "ref": "points.water_leak_cable_distance_sensor.present_value"
      }
    }

- i wish to be able to send data to DDC-1 like below:
```
"points": {
      "water_leak_detection_alarm": {
        "units": "No-units",
        "ref": "points.water_leak_detection_alarm.present_value"
      },
      "broken_cable_alarm": {
        "units": "No-units",
        "ref": "points.broken_cable_alarm.present_value"
      },
      "water_leak_cable_distance_sensor": {
        "units": "meter",
        "ref": "points.water_leak_cable_distance_sensor.present_value"
      },
      "zone_air_co2_concentration_sensor": {
        "units": "ppm",
        "ref": "points.zone_air_co2_concentration_sensor.present_value"
      }
    }
```

   where the points are aggregated (1st 3 points are from LDP-1 and the "zone..." one is from CDS-1) sending to common virtual DDC-1 and that this works with DBO telemetry validation for 2 items LDP-1 and CDS-1.

anyone have ideas, or maybe poinnt me to the correct documents or point out my mistakes?
Thanks for any info

**Comment by josephedwardchang** [comment, marked as answer]
Ok I've figured it out. Open the file tools\validators\instance_validator\tests\fake_instances\GOOD\good_links_passthrough.yaml and it will show you an example model for aggregated data being sent by a single gateway.

```
VIRTUAL-ENTITY-A:
  type: HVAC/CHWS_WDT
  id: SYSTEM/ID1234
  links:
    GATEWAY-ENTITY:
      return_water_temperature_sensor: return_water_temperature_sensor_1
      supply_water_temperature_sensor: supply_water_temperature_sensor_1
      thermal_power_capacity: thermal_power_capacity_1
      differential_pressure_specification: differential_pressure_specification_1

VIRTUAL-ENTITY-B:
  type: HVAC/CHWS_WDT
  id: SYSTEM/ID1235
  links:
    GATEWAY-ENTITY:
      return_water_temperature_sensor: return_water_temperature_sensor_2
      supply_water_temperature_sensor: supply_water_temperature_sensor_2
      thermal_power_capacity: thermal_power_capacity_2
      differential_pressure_specification: differential_pressure_specification_2

GATEWAY-ENTITY:
  type: GATEWAYS/PASSTHROUGH
  id: CDM/123456
  cloud_device_id: "foobar"
  translation:
    return_water_temperature_sensor_1:
      present_value: "points.return_water_temperature_sensor_1.present_value"
      units:
        key: "pointset.return_water_temperature_sensor_1.units"
        values:
          degrees_celsius: "degC"
    return_water_temperature_sensor_2:
      present_value: "points.return_water_temperature_sensor_2.present_value"
      units:
        key: "pointset.return_water_temperature_sensor_2.units"
        values:
          degrees_celsius: "degC"
    supply_water_temperature_sensor_1:
      present_value: "points.supply_water_temperature_sensor_1.present_value"
      units:
        key: "pointset.points.supply_water_temperature_sensor_1.units"
        values:
          degrees_celsius: "degC"
    supply_water_temperature_sensor_2:
      present_value: "points.supply_water_temperature_sensor_2.present_value"
      units:
        key: "pointset.points.supply_water_temperature_sensor_2.units"
        values:
          degrees_celsius: "degC"
    ...
```

The Gateway-Entity is the device that sends aggregated data to GCP. In my case, it is DDC-1, and all the telemetry data are listed in translation part. VIRTUAL-ENTITY-A and B are the sources for the data. Passthrough is fairly recent, so update your ontology! This works on telemetry validation and I'm using these on my config now.
