### ISSUE TITLE
Difference between `uses` and `implements`?

### ISSUE THREAD

**Issue by corymosiman12** [google/digitalbuildings#113]
In the generation of RDF from yaml, it appears that when `uses` are declared for a type, this translates into a `rdfs:subClassOf` relationship.  `uses`, however, seem like they should be data properties on a type as opposed to a superclass, where I would expect `implements` to define the superclass(es) for a type.  Can you explain a little bit more how this works / why it works this way?

**Comment by tasodorff** [comment]
Maybe I am misunderstanding, but I think the way we use those terms does operate the way you are expecting:

```
TYPE_A:
  uses:
  - data_field_a
  - data_field_b
  implements:
  - SUPERTYPE_A
  - SUPERTYPE_B
```

Here is an example from the ontology, where fields are defined on an abstract superclass (parent type in our parlance) and is then inherited by the child device upon inheritance.

```
CHWDPM:
  description: "Differential pressure monitoring for chilled water."
  is_abstract: true
  uses:
  - chilled_water_differential_pressure_sensor
```

```
CH_SS_SWTC_DX4SWC_CHWDPM:
  description: "Air cooled chiller with 4 stages cooling."
  is_canonical: true
  implements:
  - CH
  - SS
  - SWTC
  - DX4SWC
  - CHWDPM
```

This is our intention for how it should operate, so if you are seeing an instance somewhere that this is not being implement in that way please let me know. And again, if I am misunderstanding the question, please let me know and I'll try to clarify my answer.
