### ISSUE TITLE
States do not support 1:many mapping

### ISSUE THREAD

**Issue by tasodorff** [google/digitalbuildings#349]
Certain devices send multistate data that should be mappable to the same standard state in DBO. Here is an example:

```
discharge_fan_speed_mode:
  present_value: "points.discharge_fan_speed_mode.present_value"
  states:
    HIGH:
    - "1"
    - "4"
    MEDIUM:
    - "2"
    - "5"
    LOW:
    - "3"
    - "6"
    VFD: "7"
    "OFF": "0"
```

The instance validator does not support this type of 1:many definition for standard states; it will be necessary to modify it to support this mapping.
