### ISSUE TITLE
AHU with smartready fans

### ISSUE THREAD

**Issue by ghairapetian** [google/digitalbuildings#460]
### Discussed in https://github.com/google/digitalbuildings/discussions/454

<div type='discussions-op-text'>

<sup>Originally posted by **ghairapetian** January 14, 2022</sup>
Hello,

I have an AHU with 2 fans that communicate separatly to GCP.

I made an example to check how I can model that.

````
BUILDING-1:
  type: FACILITIES/BUILDING
  id: 1

AHU-1:
  type: HVAC/AHU_SSPC_SFVSC
  id: 2
  cloud_device_id: 1
  connections:
    BUILDING-1: CONTAINS
  translation:
    supply_air_static_pressure_sensor:
      present_value: "supply_air_static_pressure_sensor"
      units:
        key: "units"
        values:
          pascals: "pascals"
    supply_air_static_pressure_setpoint:
      present_value: "supply_air_static_pressure_setpoint"
      units:
        key: "units"
        values:
          pascals: "pascals"
  links:
    SF-1:
      supply_fan_run_status: run_status
      supply_fan_run_command: run_command
      supply_fan_speed_percentage_command: speed_percentage_command

SF-1:
  type: HVAC/FAN_SS_VSC
  id: 3
  cloud_device_id: 1
  connections:
    AHU-1: HAS_PART
  translation:
    speed_percentage_command:
      present_value: "speed_percentage_command"
      units:
        key: "units"
        values:
          percent: "percent"
    run_status:
      present_value: "run_status"
      states:
        ON: "1"
        OFF: "0"
    run_command:
      present_value: "run_command"
      states:
        ON: "1"
        OFF: "0"
````
Unfortunatly, the instance validator told me that **supply_air_static_pressure_sensor** and **supply_air_static_pressure_setpoint** are missing from **links** and **supply_fan_run_status**, **supply_fan_run_command** and **supply_fan_speed_percentage_command** are missing from translation. Is it possible to have a mix of links and translation in an entity ?

````
Starting config validation...

Loading config files...

Validating syntax please wait ...
Opening file: C:\Users\ghairapetian\Workspace\dbo50rda\building.yaml, please wait ...
[WARNING]: Entity GUID will be required in the future for 1.
[WARNING]: Entity GUID will be required in the future for 2.
[WARNING]: Entity GUID will be required in the future for 3.

Starting config validation...

Validating entities ...
WARNING: Entity GUID will be required in the future.
WARNING: Entity GUID will be required in the future.
Required field /supply_fan_speed_percentage_command is missing from translation
Required field /supply_fan_run_command is missing from translation
Required field /supply_fan_run_status is missing from translation
Required field /supply_air_static_pressure_sensor is missing from links        
Required field /supply_air_static_pressure_setpoint is missing from links      
AHU-1 is not a valid instance
WARNING: Entity GUID will be required in the future.
All entities validated
````</div>
