### ISSUE TITLE
The instance validator reject an apparant well formed instance

### ISSUE THREAD

**Issue by ghairapetian** [google/digitalbuildings#505]
**Describe the bug**
The instance validator reject an apparant well formed instance

**To Reproduce**
Launch the instance validation script on this instance :

```
BUILDING-1:
  type: FACILITIES/BUILDING
  guid: 1
  id: 1

TEST-1:
  type: METERS/EM_PWM_AVCM_PLPM_PVCM
  guid: 2
  id: 2
  cloud_device_id: 2
  connections:
    BUILDING-1: CONTAINS
  translation:
    power_sensor:
      present_value: points.power_sensor.present_value
      units:
        key: pointset.points.power_sensor.units
        values:
          kilowatts: kilowatts
    phase1_power_sensor:
      present_value: points.phase1_power_sensor.present_value
      units:
        key: pointset.points.phase1_power_sensor.units
        values:
          kilowatts: kilowatts
    phase2_power_sensor:
      present_value: points.phase2_power_sensor.present_value
      units:
        key: pointset.points.phase2_power_sensor.units
        values:
          kilowatts: kilowatts
    phase3_power_sensor:
      present_value: points.phase3_power_sensor.present_value
      units:
        key: pointset.points.phase3_power_sensor.units
        values:
          kilowatts: kilowatts
    energy_accumulator:
      present_value: points.energy_accumulator.present_value
      units:
        key: pointset.points.energy_accumulator.units
        values:
          watt_hours: watt_hours
    powerfactor_sensor:
      present_value: points.powerfactor_sensor.present_value
      units:
        key: pointset.points.powerfactor_sensor.units
        values:
          no_units: no_units
    average_line_current_sensor:
      present_value: points.average_line_current_sensor.present_value
      units:
        key: pointset.points.average_line_current_sensor.units
        values:
          amperes: amperes
    phase1_line_current_sensor:
      present_value: points.phase1_line_current_sensor.present_value
      units:
        key: pointset.points.phase1_line_current_sensor.units
        values:
          amperes: amperes
    phase2_line_current_sensor:
      present_value: points.phase2_line_current_sensor.present_value
      units:
        key: pointset.points.phase2_line_current_sensor.units
        values:
          amperes: amperes
    phase3_line_current_sensor:
      present_value: points.phase3_line_current_sensor.present_value
      units:
        key: pointset.points.phase3_line_current_sensor.units
        values:
          amperes: amperes
    phase1_neutral_line_voltage_sensor:
      present_value: points.phase1_neutral_line_voltage_sensor.present_value
      units:
        key: pointset.points.phase1_neutral_line_voltage_sensor.units
        values:
          volts: volts
    phase2_neutral_line_voltage_sensor:
      present_value: points.phase2_neutral_line_voltage_sensor.present_value
      units:
        key: pointset.points.phase2_neutral_line_voltage_sensor.units
        values:
          volts: volts
    phase3_neutral_line_voltage_sensor:
      present_value: points.phase3_neutral_line_voltage_sensor.present_value
      units:
        key: pointset.points.phase3_neutral_line_voltage_sensor.units
        values:
          volts: volts
    phase1_phase2_line_voltage_sensor:
      present_value: points.phase1_phase2_line_voltage_sensor.present_value
      units:
        key: pointset.points.phase1_phase2_line_voltage_sensor.units
        values:
          volts: volts
    phase2_phase3_line_voltage_sensor:
      present_value: points.phase2_phase3_line_voltage_sensor.present_value
      units:
        key: pointset.points.phase2_phase3_line_voltage_sensor.units
        values:
          volts: volts
    phase1_phase3_line_voltage_sensor:
      present_value: points.phase1_phase3_line_voltage_sensor.present_value
      units:
        key: pointset.points.phase1_phase3_line_voltage_sensor.units
        values:
          volts: volts
    average_line_neutral_voltage_sensor:
      present_value: points.average_line_neutral_voltage_sensor.present_value
      units:
        key: pointset.points.average_line_neutral_voltage_sensor.units
        values:
          volts: volts
    average_inter_line_voltage_sensor:
      present_value: points.average_inter_line_voltage_sensor.present_value
      units:
        key: pointset.points.average_inter_line_voltage_sensor.units
        values:
          volts: volts
    reactive_power_sensor:
      present_value: points.reactive_power_sensor.present_value
      units:
        key: pointset.points.reactive_power_sensor.units
        values:
          kilovolt_amperes_reactive: kilovolt_amperes_reactive
    apparent_power_sensor:
      present_value: points.apparent_power_sensor.present_value
      units:
        key: pointset.points.apparent_power_sensor.units
        values:
          kilovolt_amperes: kilovolt_amperes
```

**Expected behavior**
Instance validator script should validate all the entities.

**Screenshots**
![image](https://user-images.githubusercontent.com/83808569/155986988-a341b61c-b400-4e07-bde3-8a7a89fdaf88.png)

**OS (please complete the following information):**
OS : Windows 11
Python : 3.9.10
