### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by david-waterworth** [google/digitalbuildings#52]
How are units applied? i.e. units.yaml contains different units for flowrate with cubic_meters_per_second as STANDARD. We generally name points "Supply Air Flow" for the standard (our standard measure is l/s) and "Supply Air Flow ms" when there's a meter with a non-standard unit.

I don't see anywhere that units are associated with either fields or equipment, is this something which hasn't been finalized?

Also there's a broken link in `ontology_config.md` line #280

**Comment by tasodorff** [comment]
The `units.yaml` file indicates which subfields are linked directly to specified units of measurement. Listed under each subfield is a list of equivalent units.  We use SI as outlined in QUDT; it is not intended to be the local standard. For example, in the US we default to CFM for air or GPM for water, or, more to the point, rate of energy transfer (i.e. power) is KW, MBH, THERM/H, etc. depending on context; by converting everything to common units we remove the ambiguity of context for the purposes of storage. Upstream applications, knowing the units of storage and the conversion rates, can account for local custom. 

Noted on the broken link. I have submitted a pull request to fix it.

**Comment by david-waterworth** [comment]
Do you see the mapping between the actual BMS point to be external to your representation? For example if the application was an overlay over existing BMS(es) you'd need to know what the BMS units were (along with the object identifier/device identifier etc.). Haystack 4.0 for example seems to model the BMS as part of the ontology to some degree - they include tags to indicate if a point has curr and historised data for example. If the intent is to create a single data warehouse and exclude the ETL process from the RDF then this is probably unnecessary.

**Comment by tasodorff** [comment]
The intention is for a translation to exist between our representation and that of the BMS. The code below is an example of what a config might look like (see [here](https://github.com/google/digitalbuildings/blob/master/ontology/docs/building_config.md) for further details):

```
FCU-123:
  ...
  translation:
    zone_air_temperature_sensor:
      present_value: "temp_1"
      unit_values:
        degrees_celsius: "degC"
        degrees_fahrenheit: "degF"
    supply_air_isolation_damper_command:
      present_value: "damper_1"
      states:
        OPEN: "1"
        CLOSED: "2"
```

There is a mapping of k:v to units that the device can send and what they translate to. In this example, the translation can handle unit values of degC and degF but no K. If you wanted it to, you could add another k:v pair. You would also configure this to contain your BACnet or base system address if you were using it for a traditional BMS, based on however your JSON is configured (the expectation is that the JSON conforms to UDMI).
