### ISSUE TITLE
Deserialization fails if a lone entity is expressed in the new format

### ISSUE THREAD

**Issue by ahemphill** [google/digitalbuildings#530]
**Describe the bug**
If a .yaml configuration file contains a lone entity in the old format (name as primary key), `validator.handler.Deserialize()` returns a single-entry dictionary as expected. If the same entity is expressed in the new format (GUID as primary key), however, the method returns an empty dictionary.

**To Reproduce**
1. Save the following as `old_format.yaml`:
```
FCU-1:
  cloud_device_id: 2599571827844401
  guid: 90ebdd30-efdf-4aec-82d7-90f8e03a6792
  type: HVAC/CHWS_WDT
```
2. Run `validate.handler.Deserialize(['old_format.yaml'])`
3. Observe that it returns:
```
({'90ebdd30-efdf-4aec-82d7-90f8e03a6792': <validate.entity_instance.EntityInstance object at 0x7f8b6e0ef850>}, <ConfigMode.INITIALIZE: 'INITIALIZE'>)
```
4. Save the following as `new_format.yaml`:
```
90ebdd30-efdf-4aec-82d7-90f8e03a6792:
  cloud_device_id: 2599571827844401
  code: FCU-1
  type: HVAC/CHWS_WDT
```
5. Run `validate.handler.Deserialize(['new_format.yaml'])`
6. Observe that it returns: 
```
({}, <ConfigMode.INITIALIZE: 'INITIALIZE'>)
```
7. Add an arbitrary valid entity to `new_format.yaml` and observe that `validate.handler.Deserialize(['new_format.yaml'])` returns as expected.

**Expected behavior**
I expect `validate.handler.Deserialize()` to return a non-empty dictionary when it receives a configuration file which contains a lone entity in the new format.

**OS (please complete the following information):**
macOS 12.2.1; Python 3.7.9; HEAD at [6ebb1560f4cc16c12b9d94bca13c60afda83e893](https://github.com/google/digitalbuildings/commit/6ebb1560f4cc16c12b9d94bca13c60afda83e893)

**Additional context**
While single-entity configuration files are uncommon, they are important for testing the `scoring` tool.
