### ISSUE TITLE
Validation problem with units that exists

### ISSUE THREAD

**Issue by teamcity-vayandata** [google/digitalbuildings#565]
**Describe the bug**
I use the validation script on a yaml file but I got a error on 2 units whereas those units exists in units.yaml

**To Reproduce**
Launch the validation script on the attached yaml
**Expected behavior**
The validation script write that there is a unit problem
**Screenshots**
![image](https://user-images.githubusercontent.com/104447233/165768886-246aa1ef-e453-48ac-9443-de0a6be384a2.png)

**OS (please complete the following information):**
OS : Windows 1

**Yaml file**
[EM-test.zip](https://github.com/google/digitalbuildings/files/8583375/EM-test.zip)
1

**Comment by trav3711** [comment]
@teamcity-vayandata We have updated the ontology to how reactive and apparent power units should be formatted. For your instance to pass the instance validator, please update the standard unit as such:

```
reactive_power_sensor:
      present_value: points.reactive_power_sensor.present_value
      units:
        key: pointset.points.reactive_power_sensor.units
        values:
          kilovolt_amperes: kilovolt_amperes_reactive
    apparent_power_sensor:
      present_value: points.apparent_power_sensor.present_value
      units:
        key: pointset.points.apparent_power_sensor.units
        values:
          kilovolt_amperes: kilovolt_amperes_apparent
```
